### ISSUE TITLE
Started executables are not removed

### ISSUE THREAD

**Issue by detmagiskemuldyr** [jborean93/pypsexec#6] opened 2018-08-30 07:22 UTC
I'm trying to start a remote process, communicate with it, and close it when I don't need further information. The process opens and runs fine, but stays around after closing the PAExec. 

My code looks like the following:

```
client.connect()
client.create_service()
client.run_executable("C:\Windows\System32\cmd.exe",
                     asynchronous=True,
                   timeout_seconds = 10)

print("Started Command Prompt Service")
time.sleep(1)

client.remove_service()
#client.cleanup()
print("Removed Command Prompt Service")

client.disconnect()
print("Disconnected")
```

Running this multiple times leaves multiple cmd.exe on the remote side. It is not removed using cleanup() either.

**Comment by jborean93** [comment] 2018-09-01 05:42
The PAExec executable is opened with the `FILE_DELETE_ON_CLOSE` flag here https://github.com/jborean93/pypsexec/blob/master/pypsexec/client.py#L445. This flag tells Windows to delete the file when all handles to this file are closed so anything that was spawned from this would keep the handle open. I need to look into this a bit more but IIRC SMB didn't have an explicit delete command (could be wrong here)

**Comment by kr1shn4murt1** [comment] 2018-09-19 09:19
Hello, very nice job with this library
I'm trying to find the right syntax to achieve with pypsexec the same result as this psexec command
psexec -s -h -i \\192.168.92.135 -u domain\user -p password cmd

When I use the psexec command it opens a cmd window in the remote computer which can be seen by the user and interact with it 

I have tried several options and combinations, switching true and false values with no success:

This is my code:

c= Client(equipo_Remoto, username=user, password=passwd)
c.connect()

try:
	c.create_service()

	c.run_executable(r'cmd.exe', interactive= True, run_elevated= True, use_system_account= True, show_ui_on_win_logon= True, asynchronous= False, load_profile= True)
finally:
	c.remove_service()
	c.disconnect()

Thanks

**Comment by jborean93** [comment] 2018-09-19 11:48
@kr1shn4murt1 I've put your comment in a separate issue as it is unrelated to this one https://github.com/jborean93/pypsexec/issues/7.

**Comment by smrinalsingh** [comment] 2019-05-29 05:56
I have the same issue. Is there a way to force close the handles marked for delete, yet?

Here is the background: I've created a Tk based application which would first check if the remote machine is up and then there is a **validation** method which would create the object and validate the hostname against the one provided. 

This object is a global variable which can be accessed by the other methods too hence when the user presses the '**Reset**' button on this Tk application, it is supposed to do the _cleanup_, _remove_service_, _disconnect_ and then reassign the value of this object variable to **None**.

Now, after **reset** too, wherein everything is supposed to be deleted and cleaned up, the handle still remains open which would make windows wait for it to close and then delete the associated files on the remote machine, as you've already mentioned.

Were you able to come up with any workaround? As of now, I've got to restart the application. I don't understand how the remote machine knows that the application was closed and further deletes the related files? I mean, I've even reassigned the value of the PS obj to 'None' after cleanup commands are run. There is nothing related to the module which could in turn tell the remote machine that the application was closed and hence to proceed with the deletion. Any thoughts?

**Comment by jborean93** [comment] 2019-08-19 04:08
Sorry for the delay on this one, I've just re-read the issue and it looks like it's around the process that is being spawned is sticking around even after removing the service and PAExec executable. Because you are setting the `asynchronous=True` kwarg this is as by design as the process is being created and being detached from the PAExec service. This means it's lifetime is completely separate from the service and will continue to run even once the service is removed.

The same behaviour applies to psexec, you can do `psexec.exe \\computer -d cmd.exe` you can see that the process continues to run even though the PSExec service is no longer there. This is not related to the `FILE_DELETE_ON_CLOSE` flag. That flag is around the actual executable to the service being removed on cleanup which is what the `.remove_service()` function is for.

If you need to ensure the process does not outlive the service you will need to run another process yourself to kill that process based on PID before you call `.remove_service()`. The return value of `run_executable()` is a tuple of `(stdout, stderr, rc)` where `rc` is the PID if `asynchronous=True` is set. You can use that value alongside [Stop-Process](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/stop-process?view=powershell-6) or `taskkill` to stop that process at your cleanup stage.

Because this is behaviour as intended I am going to close this issue. Keeping a mapping between processes that have beens tarted asynchronous and trying to clean them up later is not something I think belongs in this library. It should be up to the caller to manage those async processes and not pypsexec.

**Closed by jborean93** 2019-08-19 04:08 UTC
